// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ValueExpr } from "./ValueExpr";

/**
 * `agent.invoke` — サンドボックスで agent-core を実行（best-effort・wasm ティア固定）。
 *
 * サンドボックス設定は**縮小のみ**（実効 = 実行主体 ReBAC ∩ declared_scopes ∩ 本設定）。
 * `mount_scope`/`allowed_tools`/`model`/`max_tokens` は Phase 5 フルツール構成との結線
 * （enforcement）実装時に追加する（効かない制限を UI に約束しない・fail-closed）。
 */
export type AgentInvokeParams = { 
/**
 * エージェントへの指示文。
 */
instruction: ValueExpr, 
/**
 * egress allowlist（リテラルのみ・縮小のみ・省略時は外部通信なし）。
 */
egress_allowlist: Array<string>, 
/**
 * 実行時間上限（秒）。
 */
max_duration_sec?: ValueExpr, };
