// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 指数バックオフ（full jitter は実行時・engine.md §7）。
 */
export type Backoff = { base_sec: number, max_sec: number, jitter: boolean, };
