// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Condition } from "./Condition";

/**
 * `control.branch` — 条件を評価して `true`/`false` ポートを確定する。
 */
export type BranchParams = { 
/**
 * 判定条件（条件木・ir.md §3.3）。
 */
condition: Condition, };
