// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 比較演算子（閉じた集合・ir.md §3.3）。
 */
export type CmpOp = "eq" | "neq" | "lt" | "lte" | "gt" | "gte" | "in" | "contains" | "starts_with" | "ends_with" | "exists" | "is_null" | "matches";
