// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CmpOp } from "./CmpOp";
import type { ValueExpr } from "./ValueExpr";

/**
 * 単項比較。`left` を評価し `op` と `right`（省略可: exists/is_null）で判定する。
 */
export type Comparison = { left: ValueExpr, op: CmpOp, right: ValueExpr | null, };
