// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Comparison } from "./Comparison";

/**
 * 条件木（`all`/`any`/`not` 合成＋閉じた op・ir.md §3.3）。
 */
export type Condition = { "all": Array<Condition> } | { "any": Array<Condition> } | { "not": Condition } | { "cmp": Comparison };
