// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ValueExpr } from "./ValueExpr";

/**
 * `csv.patch` — CSV をパッチ編集して新バージョンを保存（editor・EngineDedup）。
 */
export type CsvPatchParams = { 
/**
 * 対象 CSV ファイル id。
 */
file: ValueExpr, 
/**
 * 編集前の版（node.version・楽観ロックの base）。
 */
base_rev: ValueExpr, 
/**
 * パッチ操作の配列（tabular の `PatchOp` に解決される JSON 値）。
 */
ops: ValueExpr, };
