// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ValueExpr } from "./ValueExpr";

/**
 * `csv.query` — CSV への読み取り専用 SQL（テーブル名 `data`・viewer・pure）。
 */
export type CsvQueryParams = { 
/**
 * 対象 CSV ファイル id（UUID に解決される値）。
 */
file: ValueExpr, 
/**
 * 読み取り専用 SELECT（テーブル名 `data`）。
 */
sql: ValueExpr, };
