// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ValueExpr } from "./ValueExpr";

/**
 * `csv.write` — 新規 CSV を保存（保存先フォルダの作成権限・EngineDedup）。
 */
export type CsvWriteParams = { 
/**
 * 保存先フォルダ id（省略時は実行主体のルート）。
 */
folder?: ValueExpr, 
/**
 * ファイル名（`.csv` は自動付与）。
 */
name: ValueExpr, 
/**
 * CSV 本文（ヘッダ行＋データ行）。
 */
content: ValueExpr, };
