// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 1 エッジ（`from` ノードの `from_port` → `to` ノード）。
 *
 * join 以外の入エッジは 1 本制約（V2）。エッジ状態は永続化せず taken_ports から導出（engine.md §2.3）。
 */
export type Edge = { 
/**
 * 出力元ノード id。
 */
from: string, 
/**
 * 出力ポート名（省略時 `out`。branch は `true`/`false`、switch は case 名、error は `error`）。
 */
from_port: string, 
/**
 * 入力先ノード id。
 */
to: string, };
