// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Condition } from "./Condition";

/**
 * イベントトリガ（source＋scope＋filter・ir.md §6.2）。
 */
export type EventTrigger = { 
/**
 * イベント source（閉集合・V3 で照合。Stage A は storage.write のみ有効）。
 */
source: EventSource, 
/**
 * scope（テーブル/フォルダ束縛必須・全購読禁止）。
 */
scope: unknown, 
/**
 * filter（条件木・省略可）。
 */
filter?: Condition, };
