// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * イベントトリガの source 閉集合（Stage A は storage.write のみ有効）。
 */
export type EventSource = "storage.write" | "data.record.created" | "data.record.updated" | "data.transition";
