// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `$from` 参照（`{ "$from": "...", "path": "<JSON Pointer>", "default": ... }`・ir.md §3.1）。
 */
export type FromRef = { 
/**
 * source: `input` / `trigger` / `nodes.<id>.output` / `run` / `each`（`each.item`/`each.index`）。
 */
$from: string, 
/**
 * JSON Pointer（省略時は source 全体）。
 */
path: string | null, 
/**
 * 解決失敗時の既定値（無ければ解決失敗で step 失敗）。
 */
default: unknown, };
