// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SecretAttach } from "./SecretAttach";

/**
 * secret 参照（参照名のみ・解決/宛先束縛検証/注入はエンジンが実行直前に行う）。
 */
export type HttpSecretRef = { 
/**
 * secret の参照名（V4 で存在＋宛先束縛を照合）。
 */
name: string, 
/**
 * 添付方式（省略時 bearer）。
 */
attach?: SecretAttach, };
