// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HttpMethod } from "./HttpMethod";
import type { HttpSecretRef } from "./HttpSecretRef";
import type { RedirectPolicy } from "./RedirectPolicy";
import type { ValueExpr } from "./ValueExpr";

/**
 * `http.request` — egress allowlist × シークレット宛先束縛の AND（best-effort・ir.md §7.2）。
 */
export type HttpRequestParams = { 
/**
 * HTTP メソッド（省略時 GET）。
 */
method?: HttpMethod, 
/**
 * ベース URL。**ホスト部はリテラル必須**（`$from`/`$template` 不可・String 型が
 * 構造的に拒否する＝PIT-36 の型防御。パスは `path_suffix` で可変にできる）。
 */
url: string, 
/**
 * URL 末尾に連結するパス（可変部）。
 */
path_suffix?: ValueExpr, 
/**
 * リクエストボディ。
 */
body?: ValueExpr, 
/**
 * 添付する secret（参照名のみ）。
 */
secret?: HttpSecretRef, 
/**
 * リダイレクトの扱い（既定 deny・Stage A は deny のみ）。
 */
redirect?: RedirectPolicy, };
