// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 冪等性区分（ir.md §7・UI が「再実行で二重になり得るか」を表示する）。
 */
export type IdempotencyClass = "pure" | "engine_dedup" | "best_effort";
