// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 対話トリガ（UI/チャット起動）。
 */
export type InteractiveTrigger = { 
/**
 * 表示ラベル（省略可）。
 */
label: string | null, };
