// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JoinMode } from "./JoinMode";

/**
 * `control.join` — 待ち合わせ（発火判定の実行時セマンティクスは engine.md §4）。
 */
export type JoinParams = { 
/**
 * 待ち合わせモード（既定 all）。
 */
mode?: JoinMode, };
