// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ValueExpr } from "./ValueExpr";

/**
 * `llm.invoke` — llm-gateway 直行（pure・課金あり）。
 *
 * `model` はモデルカタログ照合（V3）が必須性を担保する（カタログ未設定環境のみ省略可）。
 * `effort`/`output_schema` は llm-gateway 経路の enforcement 実装時に追加する（契約に
 * 「効かないフィールド」を含めない方針・ir.md §7.3）。
 */
export type LlmInvokeParams = { 
/**
 * モデル id（テナントのモデルカタログへ保存時照合・実行時再照合）。
 */
model?: string, 
/**
 * ユーザープロンプト。
 */
prompt: ValueExpr, 
/**
 * システムプロンプト（省略可）。
 */
system?: ValueExpr, 
/**
 * 出力トークン上限（省略時は gateway 既定）。
 */
max_tokens?: ValueExpr, };
