// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * map 領域内の要素失敗の扱い（engine.md §4.5）。
 */
export type MapItemError = "fail_map" | "collect";
