// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MapItemError } from "./MapItemError";
import type { ValueExpr } from "./ValueExpr";

/**
 * `control.map` — 配列要素ごとに領域を動的 fan-out する（engine.md §4.5）。
 */
export type MapParams = { 
/**
 * 繰り返す配列（$from 参照が典型）。
 */
items: ValueExpr, 
/**
 * 要素の同時実行上限（既定 10・Stage A はワーカー並列数が実効上限）。
 */
max_concurrency?: number, 
/**
 * 要素失敗の扱い（既定 fail_map）。
 */
on_item_error: MapItemError, };
