// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ノード type の閉集合。未実装 variant は保存時に V3 が Stage で弾く（予約語彙）。
 */
export type NodeType = "control.branch" | "control.switch" | "control.join" | "control.map" | "control.wait" | "storage.read" | "storage.write" | "storage.list" | "rag.search" | "llm.invoke" | "agent.invoke" | "http.request" | "script.run" | "workflow.start" | "csv.query" | "csv.patch" | "csv.write" | "data.query" | "data.record.create" | "data.record.update" | "data.transition" | "notify.send" | "skill.invoke" | "control.loop" | "control.assert" | "debug.log" | "transform.template" | "transform.parse" | "transform.serialize" | "transform.regex" | "transform.map" | "transform.filter" | "transform.reduce" | "sheet.read" | "sheet.write" | "sheet.append" | "doc.read" | "doc.edit" | "doc.comment" | "memory.get" | "memory.set" | "event.publish" | "workflow.call" | "llm.embed" | "llm.extract" | "ai.review" | "ai.eval" | "ai.ocr" | "ai.image.analyze" | "ai.image.generate" | "ai.transcribe" | "ai.speech" | "graphql.query" | "sandbox.exec" | "human.approval";
