// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ノード type の閉集合（Stage A 実装分のみ variant 化）。
 */
export type NodeType = "control.branch" | "control.switch" | "control.join" | "control.map" | "control.wait" | "storage.read" | "storage.write" | "storage.list" | "rag.search" | "llm.invoke" | "agent.invoke" | "http.request" | "script.run" | "workflow.start";
