// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OnError } from "./OnError.js";
import type { RetryPolicy } from "./RetryPolicy.js";

/**
 * 1 ノード（type ごとの params は検証時に vocab＋個別スキーマで照合）。
 */
export type Node = { 
/**
 * ワークフロー内一意の id。
 */
id: string, 
/**
 * ノード種（`storage.write` 等・vocab の閉集合へ V3 照合）。
 */
type: string, 
/**
 * 表示名（省略可）。
 */
label: string | null, 
/**
 * map 領域内なら親 map の id、領域外は null（ir.md §5）。
 */
parent: string | null, 
/**
 * ノード種ごとのパラメータ（codegen が正・検証時に個別照合）。
 */
params: unknown, 
/**
 * リトライポリシ（既定 max_attempts=1＝リトライなし）。
 */
retry: RetryPolicy, 
/**
 * ステップタイムアウト（秒・省略時はノード種の既定）。
 */
timeout_sec: number | null, 
/**
 * エラー時の扱い（既定 fail_run）。
 */
on_error: OnError, };
