// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * パレットのカテゴリ（表示順に定義）。
 */
export type NodeCategory = "control" | "storage" | "ai" | "external" | "developer" | "workflow" | "data" | "notify" | "skill" | "transform" | "office" | "memory";
