// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IdempotencyClass } from "./IdempotencyClass";
import type { NodeCategory } from "./NodeCategory";

/**
 * カタログの 1 エントリ（1 ノード種）。
 */
export type NodeCatalogEntry = { 
/**
 * ノード種（IR の `type` 値）。
 */
type: NodeType, 
/**
 * パレットのカテゴリ。
 */
category: NodeCategory, 
/**
 * カテゴリの日本語見出し（表示用・category から導出）。
 */
category_label_ja: string, 
/**
 * ノードの日本語ラベル。
 */
label_ja: string, 
/**
 * 1 行説明（IT に詳しくない利用者向け）。
 */
description_ja: string, 
/**
 * 静的な出力ポート（switch は cases から動的導出のため空＋`dynamic_ports`）。
 * `on_error=continue` の `error`・wait(event, on_timeout=continue) の `timeout` は
 * 設定から導出する構造ポート（ir.md §5.2）でありここに含まない。
 */
output_ports: Array<string>, 
/**
 * 出力ポートが params から動的に決まるか（control.switch のみ）。
 */
dynamic_ports: boolean, 
/**
 * 入エッジを複数受けられるか（control.join のみ・V2 の入エッジ 1 本制約の例外）。
 */
multi_input: boolean, 
/**
 * 要求スコープ（declared_scopes への宣言が必要・None は scope 天井対象外）。
 */
required_scope: Scope | null, 
/**
 * 現ステージで保存・実行できるか（false は予約語彙＝UI は「近日対応」）。
 */
available: boolean, 
/**
 * 冪等性区分。
 */
idempotency: IdempotencyClass, 
/**
 * step timeout の既定秒（ir.md §7 の表・未規定の予約語彙と制御ノードは None）。
 */
timeout_default_sec: number | null, 
/**
 * step timeout の上限秒。
 */
timeout_max_sec: number | null, };
