// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TriggerOverflow } from "./TriggerOverflow.js";

/**
 * 実行ポリシ（ir.md §2）。
 */
export type Policies = { 
/**
 * run タイムアウト（秒・既定 3 日・最大 30 日）。
 */
run_timeout_sec: number, 
/**
 * 同時実行 run 上限（既定 10）。
 */
max_parallel_runs: number, 
/**
 * トリガ溢れ時の扱い（queue 既定 / skip）。
 */
on_trigger_overflow: TriggerOverflow, };
