// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ValueExpr } from "./ValueExpr";

/**
 * `rag.search` — permission-aware 検索（必要スコープは `rag.query`・pure）。
 */
export type RagSearchParams = { 
/**
 * 検索クエリ。
 */
query: ValueExpr, 
/**
 * 取得件数（省略時は検索サービスの既定）。
 */
top_k?: ValueExpr, };
