// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * リダイレクトの扱い。Stage A は非追従のみ（`follow_stripped` は追従先の宛先束縛
 * 再照合の実装時に variant 追加する・PIT-36・偽装しない）。
 */
export type RedirectPolicy = "deny";
