// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Backoff } from "./Backoff";

/**
 * リトライポリシ（ir.md §4・PIT-31 思想で既定リトライなし）。
 */
export type RetryPolicy = { 
/**
 * 最大試行回数（既定 1＝リトライなし）。
 */
max_attempts: number, 
/**
 * バックオフ（省略時は指数の既定）。
 */
backoff: Backoff, };
