// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * run_event の種（engine.md §3.3 の 12 種）。
 */
export type RunEventKind = "run_started" | "step_ready" | "step_started" | "step_succeeded" | "step_failed" | "step_retrying" | "step_skipped" | "step_waiting" | "step_woken" | "run_succeeded" | "run_failed" | "run_cancelled";
