// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * run_event の種（engine.md §3.3 の 12 種）。DB の run_event.kind に書く値と一致。
 */
export type RunEventKind = "run.started" | "step.ready" | "step.started" | "step.succeeded" | "step.failed" | "step.retrying" | "step.skipped" | "step.waiting" | "step.woken" | "run.succeeded" | "run.failed" | "run.cancelled";
