// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * run_event の種（engine.md §3.3 の 12 種）。
 *
 * serde/TS の表現は `as_str()`（DB の run_event.kind に書く値）と一致させる（ドット表記）。
 * snake_case 自動変換に任せると `run_started` になり DB 値 `run.started` と食い違うため明示 rename。
 */
export type RunEventKind = "run.started" | "step.ready" | "step.started" | "step.succeeded" | "step.failed" | "step.retrying" | "step.skipped" | "step.waiting" | "step.woken" | "run.succeeded" | "run.failed" | "run.cancelled";
