// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Catchup } from "./Catchup.js";

/**
 * スケジュールトリガ（cron 5 フィールド＋IANA tz）。
 */
export type ScheduleTrigger = { 
/**
 * cron 式（5 フィールド）。
 */
cron: string, 
/**
 * IANA タイムゾーン（必須）。
 */
tz: string, 
/**
 * misfire 時の扱い（skip 既定 / none。all は v1 でやらない）。
 */
catchup: Catchup, };
