// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 宣言スコープ（declared_scopes）の閉集合。IR が宣言できる権限の天井。
 */
export type Scope = "data.read" | "data.write" | "storage.read" | "storage.write" | "rag.query" | "notify.send" | "http.egress" | "workflow.start";
