// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScriptSourceSpec } from "./ScriptSourceSpec.js";
import type { ValueExpr } from "./ValueExpr.js";

/**
 * `script.run` — shiki script の 1 回有界実行（ir.md §7.6）。
 */
export type ScriptRunParams = { 
/**
 * スクリプトソース。
 */
source: ScriptSourceSpec, 
/**
 * `main(input)` へ渡す入力（省略時はステップ入力）。
 */
input?: ValueExpr, };
