// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * script の source（inline / artifact のちょうど一方）。
 *
 * untagged enum は serde の `deny_unknown_fields` と併用できないため、フラット struct
 * ＋ [`check_exactly_one`](Self::check_exactly_one) で厳密性を保つ。
 */
export type ScriptSourceSpec = { 
/**
 * インラインソース（≤64KB・保存時に swc パース検証 V6）。
 */
inline?: string, 
/**
 * artifact 参照（`script:<name>@<ver>`・version 固定）。
 */
artifact?: string, };
