// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SecretAttachKind } from "./SecretAttachKind";

/**
 * secret の添付指定。
 */
export type SecretAttach = { 
/**
 * 添付方式。
 */
kind: SecretAttachKind, 
/**
 * kind=header 時のヘッダ名（省略時 Authorization）。
 */
header?: string, };
