// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ValueExpr } from "./ValueExpr";

/**
 * `skill.invoke` — インストール済み skill の実行（ir.md §7.7・#344 Task 10.1b）。
 *
 * `skill` は `skill:<name>@<version>` のリテラル参照（保存時にレジストリ＋保存ユーザーの
 * インストール集合へ照合＝V4・実行時に実行主体 ReBAC で再検証＝fail-closed）。
 * skill が `.shiki` script を持てば script-runtime で実行し、instructions のみなら
 * agent.invoke 経路（サンドボックス）で実行する（新しい実行機構は作らない）。
 */
export type SkillInvokeParams = { 
/**
 * `skill:<name>@<version>` のリテラル参照（$from 不可・照合可能性のため）。
 */
skill: string, 
/**
 * skill への入力（省略時はノード入力をそのまま渡す）。
 */
input?: ValueExpr, };
