// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ValueExpr } from "./ValueExpr";

/**
 * `storage.read` — ファイル読み（≤10MB・pure）。
 */
export type StorageReadParams = { 
/**
 * 読むファイル id（UUID に解決される値）。
 */
file: ValueExpr, };
