// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ValueExpr } from "./ValueExpr";

/**
 * `storage.write` — ファイル書き（新バージョン追記・engine-dedup で高々 1 回）。
 */
export type StorageWriteParams = { 
/**
 * 書き先フォルダ id（省略時は実行主体のルート）。
 */
folder?: ValueExpr, 
/**
 * ファイル名。
 */
name: ValueExpr, 
/**
 * 内容（文字列＝UTF-8・`{ "base64": ... }`＝バイナリ・その他 JSON＝直列化）。
 */
content: ValueExpr, 
/**
 * Content-Type（省略時 application/octet-stream）。
 */
content_type?: ValueExpr, };
