// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SwitchCase } from "./SwitchCase";
import type { ValueExpr } from "./ValueExpr";

/**
 * `control.switch` — 値を case とリテラル照合し、一致 port（なければ `default`）へ。
 */
export type SwitchParams = { 
/**
 * 照合する値。
 */
value: ValueExpr, 
/**
 * case 一覧（上から順に照合）。
 */
cases: Array<SwitchCase>, };
