// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `control.switch` の 1 case（値がリテラル一致したらその port を取る）。
 */
export type SwitchCase = { 
/**
 * 一致時に取る出力ポート名。
 */
port: string, 
/**
 * 一致判定するリテラル値。
 */
equals: unknown, };
