// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ValueExpr } from "./ValueExpr.js";

/**
 * `$template` 文字列組み立て（`{name}` は vars のキーのみ・ir.md §3.2）。
 */
export type TemplateExpr = { $template: string, vars: { [key in string]?: ValueExpr }, };
