// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventTrigger } from "./EventTrigger.js";
import type { InteractiveTrigger } from "./InteractiveTrigger.js";
import type { ScheduleTrigger } from "./ScheduleTrigger.js";

/**
 * トリガ（`nodes` とは別セクション・dnd 上は擬似ノード）。
 */
export type Trigger = { "kind": "schedule" } & ScheduleTrigger | { "kind": "event" } & EventTrigger | { "kind": "interactive" } & InteractiveTrigger;
