// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * トリガ種別（run の実行主体決定・engine.md §6）。
 */
export type TriggerKind = "schedule" | "event" | "interactive";
