// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 検証エラー（コード＋メッセージ＋位置）。dnd がノード/エッジに紐付けて表示する。
 */
export type ValidationError = { 
/**
 * エラーコード（例: `ir.schema_violation`）。
 */
code: string, 
/**
 * 人向けメッセージ。
 */
message: string, 
/**
 * 紐付くノード id（該当時）。
 */
node_id: string | null, 
/**
 * 紐付くエッジ（該当時・`from -> to`）。
 */
edge: string | null, 
/**
 * IR 内の位置（`/params/...` の JSON Pointer 風・該当時）。dnd がフォームフィールドへ写像する。
 */
path: string | null, };
