// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FromRef } from "./FromRef";
import type { TemplateExpr } from "./TemplateExpr";

/**
 * パラメータ値（リテラル / `$from` / `$template`）。
 */
export type ValueExpr = FromRef | TemplateExpr | unknown;
