// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Condition } from "./Condition";
import type { ValueExpr } from "./ValueExpr";
import type { WaitKind } from "./WaitKind";
import type { WaitTimeout } from "./WaitTimeout";

/**
 * `control.wait` — 時間/イベントを durable に待つ（ir.md §7.5・engine.md §9）。
 *
 * kind タグ付き enum は serde の `deny_unknown_fields` と併用できないため、フラット struct
 * ＋ [`check_cross_fields`](Self::check_cross_fields)（kind ごとの必須/禁止）で厳密性を保つ。
 * JSON 表現は仕様（`{ "kind": "event", "source": ..., ... }`）と同一。
 */
export type WaitParams = { 
/**
 * 待ち方（duration / until / event）。
 */
kind: WaitKind, 
/**
 * kind=duration: 待つ秒数（非負）。
 */
duration_sec?: ValueExpr, 
/**
 * kind=until: 起床時刻（RFC3339）。
 */
until?: ValueExpr, 
/**
 * kind=event: 待つイベント source（閉集合・トリガと同じ語彙）。
 */
source?: EventSource | null, 
/**
 * kind=event: scope 束縛（`{ "folder": "<uuid>" }`・祖先束縛で照合）。
 */
scope?: unknown, 
/**
 * kind=event: 追加 filter（条件木・fail-closed 評価）。
 */
filter?: Condition, 
/**
 * kind=event: 待ちの上限秒（省略は無期限）。
 */
timeout_sec?: ValueExpr, 
/**
 * kind=event: timeout 時の扱い（既定 fail）。
 */
on_timeout?: WaitTimeout, };
