// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `control.wait` の kind（duration / until / event）。
 */
export type WaitKind = "duration" | "until" | "event";
