// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ValueExpr } from "./ValueExpr";

/**
 * `workflow.start` — 別ワークフロー起動（fire-and-forget・起動 1 回保証）。
 */
export type WorkflowStartParams = { 
/**
 * 起動するワークフロー name。
 */
name: ValueExpr, 
/**
 * 子 run への入力。
 */
input?: ValueExpr, };
