// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Edge } from "./Edge.js";
import type { Node } from "./Node.js";
import type { Policies } from "./Policies.js";
import type { Trigger } from "./Trigger.js";

/**
 * IR エンベロープ（トップレベル・ir.md §2）。
 *
 * `deny_unknown_fields` によりフィールド追加でも `ir_version` を上げる（deny-unknown 方針）。
 */
export type WorkflowIr = { 
/**
 * IR バージョン（単調増加・未知の版は保存拒否・§9）。
 */
ir_version: number, 
/**
 * ワークフロー名（`^[a-z][a-z0-9-]{0,63}$`・tenant 内一意は artifact 層が担保）。
 */
name: string, display_name: string | null, description: string | null, 
/**
 * 宣言スコープ（権限の天井・codegen 語彙へ V3 照合）。
 */
declared_scopes: Array<string>, 
/**
 * トリガ（schedule / event / interactive）。
 */
triggers: Array<Trigger>, 
/**
 * 対話トリガの入力スキーマ（JSON Schema サブセット・省略可）。
 */
input_schema: unknown, 
/**
 * ノード。
 */
nodes: Array<Node>, 
/**
 * エッジ。
 */
edges: Array<Edge>, 
/**
 * 実行ポリシ（省略時全既定値）。
 */
policies: Policies, };
