// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ミニアプリへ貸せる能力スコープ（Task 9.1・公開 API ゲートウェイの能力面）。
 *
 * 各操作はリソース束縛＋per-call OpenFGA に従う（スコープは上限・実認可は ReBAC）。
 * storage/data/rag/identity/events/notify/llm/agent の 8 能力を薄く再公開する。
 */
export type CapabilityScope = "storage.read" | "storage.write" | "data.read" | "data.write" | "data.schema" | "rag.query" | "identity.read" | "events.subscribe" | "notify.send" | "llm.invoke" | "agent.invoke";
