// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ループが**横取りする**メタツールの名前（`Tool` として dispatch されない・[`ToolName`] の外）。
 *
 * モデルには通常のツールとして見えるため、UI の表示辞書もこの名前で引く（TS へ生成する）。
 */
export type MetaToolName = "plan" | "tool_search";
