//! HTTP ルートハンドラ群。

pub mod admin;
pub mod app_install;
pub mod app_platform;
pub mod artifacts;
pub mod auth;
pub mod chat;
pub mod chat_approval;
pub mod chat_dto;
pub mod chat_notes;
pub(crate) mod chat_selection;
pub mod collab;
pub mod data;
pub mod data_fsm;
pub mod data_records;
pub mod data_views;
pub mod directory;
pub mod documents;
pub mod file_versions;
pub mod files;
pub mod folders;
pub mod me;
pub mod mini_apps;
pub mod office;
pub mod search;
pub mod secrets;
pub mod share_links;
pub mod shares;
pub mod skills;
pub(crate) mod sse_util;
pub mod tabular;
pub mod ui_actions;
pub mod ui_specs;
pub mod workflows;

pub use me::get_me;
