// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UiNode } from "./UiNode";

/**
 * アコーディオンの 1 節（子ツリーを持つ）。
 */
export type AccordionItem = { title: string, 
/**
 * 既定で開くか。
 */
open: boolean, children: Array<UiNode>, };
