// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccordionItem } from "./AccordionItem";

/**
 * アコーディオン（折りたたみ節）。
 */
export type AccordionProps = { items: Array<AccordionItem>, };
