// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HandlerBinding } from "./HandlerBinding";
import type { ToolBinding } from "./ToolBinding";
import type { WorkflowBinding } from "./WorkflowBinding";

/**
 * アクション束縛（3 系統の閉集合）。
 */
export type ActionBinding = { "type": "tool" } & ToolBinding | { "type": "handler" } & HandlerBinding | { "type": "workflow" } & WorkflowBinding;
