// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 宣言済みアクションへの参照（id のみ・束縛定義はクライアントから送れない）。
 */
export type ActionRef = { 
/**
 * [`UiSpecDoc::actions`] 内の束縛 id。
 */
action: string, };
