// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BadgeItem } from "./BadgeItem";

/**
 * バッジ列（タグ/ラベルの集まり）。
 */
export type BadgeListProps = { badges: Array<BadgeItem>, };
