// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BadgeTone } from "./BadgeTone";

/**
 * バッジ 1 件。
 */
export type BadgeItem = { label: string, tone: BadgeTone, };
