// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * バッジのトーン。
 */
export type BadgeTone = "neutral" | "info" | "success" | "warning" | "danger";
