// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionRef } from "./ActionRef";
import type { ButtonVariant } from "./ButtonVariant";

/**
 * ボタン（押下は宣言済みアクションのみ）。
 */
export type ButtonProps = { label: string, on_click: ActionRef, variant: ButtonVariant, };
