// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * callout のトーン（意味的バリアントのみ）。
 */
export type CalloutTone = "info" | "success" | "warning" | "danger";
