// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CalloutTone } from "./CalloutTone";

/**
 * 注意喚起カード（info/success/warning/danger のトーン）。
 */
export type CalloutProps = { tone: CalloutTone, title: string | null, text: string, };
