// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * セル値（プリミティブのみ・HTML/オブジェクトは表現不可能）。
 */
export type CellValue = string | number | boolean;
