// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * チャート種（vega-lite 的サブセット・design §4.7）。
 */
export type ChartKind = "bar" | "line" | "area" | "pie";
