// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * データ点 1 件（カテゴリ x ＋ 値 y ＋ 任意の系列名）。
 */
export type ChartPoint = { x: string, y: number, 
/**
 * 複数系列チャートの系列名（単一系列なら省略）。
 */
series: string | null, };
