// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * データ点 1 件（カテゴリ x ＋ 値 y ＋ 任意の系列名）。
 */
export type ChartPoint = { x: string, y: number, 
/**
 * 複数系列チャートの系列名（単一系列なら省略）。
 */
series: string | null, 
/**
 * 散布図（`scatter`）の数値 x。省略時は各データ点の配列インデックスを x に使い、
 * `x`（文字列）はツールチップのラベルになる。他種では無視される。
 */
xv: number | null, };
