// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SelectOption } from "./SelectOption";

/**
 * 複数選択（チェックボックス群）。
 */
export type CheckboxGroupProps = { id: string, label: string, options: Array<SelectOption>, 
/**
 * 既定で選択済みの value 群。
 */
default: Array<string>, required: boolean, 
/**
 * 「その他」自由記述を許す。
 */
allow_other: boolean, };
