// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * コードブロック（表示専用・実行しない）。
 */
export type CodeBlockProps = { code: string, 
/**
 * 言語ヒント（シンタックスハイライト用・任意）。
 */
language: string | null, };
