// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 信頼コンポーネント・カタログ（Task 6.2）。
 *
 * [`UiNode`](crate::spec::UiNode) の serde タグ（`component`）と 1:1 対応する
 * （対応は `UiNode::kind()` に単一化し、drift はテストで固定）。
 * `text_input` / `select` はフォーム部品としてのみ出現する（[`FormField`](crate::spec::FormField)）。
 */
export type ComponentKind = "container" | "text" | "link" | "form" | "text_input" | "select" | "checkbox" | "radio" | "date" | "slider" | "rating" | "button" | "table" | "chart" | "stat" | "callout" | "accordion" | "tabs" | "stepper" | "badge_list" | "key_value" | "code_block" | "question_card" | "map" | "image";
