// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 比較の 1 観点。`values` は `columns` と同数。
 */
export type ComparisonRow = { label: string, values: Array<string>, };
