// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComparisonRow } from "./ComparisonRow";

/**
 * 比較カード（2〜N 列の項目別比較表）。
 */
export type ComparisonProps = { title: string | null, 
/**
 * 比較対象（列見出し）。
 */
columns: Array<string>, rows: Array<ComparisonRow>, 
/**
 * 推し列の index（強調表示・任意）。
 */
highlight: number | null, };
