// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 部品への固定参照（常に明示ピン）。
 */
export type ComponentPin = { artifact_id: string, 
/**
 * JSON 経由の数値のため TS では number（bigint にしない）。
 */
version: number, };
