// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Layout } from "./Layout";
import type { UiNode } from "./UiNode";

/**
 * 子要素を縦/横に並べるコンテナ。
 */
export type ContainerProps = { title: string | null, layout: Layout, children: Array<UiNode>, };
