// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 日付（`range=true` で期間・値は ISO 文字列）。
 */
export type DateProps = { id: string, label: string, 
/**
 * 期間選択（開始/終了）にする。
 */
range: boolean, min: string | null, max: string | null, required: boolean, default: string | null, };
