// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * few-shot の 1 対。
 */
export type FewShotExample = { user: string, assistant: string, };
