// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CheckboxGroupProps } from "./CheckboxGroupProps.js";
import type { DateProps } from "./DateProps.js";
import type { RadioGroupProps } from "./RadioGroupProps.js";
import type { RatingProps } from "./RatingProps.js";
import type { SelectProps } from "./SelectProps.js";
import type { SliderProps } from "./SliderProps.js";
import type { TextInputProps } from "./TextInputProps.js";

/**
 * フォーム部品（`component` タグはカタログ語彙 `text_input` / `select` と共有）。
 */
export type FormField = { "component": "text_input" } & TextInputProps | { "component": "select" } & SelectProps | { "component": "checkbox" } & CheckboxGroupProps | { "component": "radio" } & RadioGroupProps | { "component": "date" } & DateProps | { "component": "slider" } & SliderProps | { "component": "rating" } & RatingProps;
