// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionRef } from "./ActionRef";
import type { FormField } from "./FormField";

/**
 * フォーム（送信は宣言済みアクションのみ）。
 */
export type FormProps = { 
/**
 * フォーム id（文書内で一意）。
 */
id: string, title: string | null, 
/**
 * 送信先アクション（宣言済み束縛の参照のみ）。
 */
submit: ActionRef, fields: Array<FormField>, submit_label: string | null, };
