// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SelectProps } from "./SelectProps";
import type { TextInputProps } from "./TextInputProps";

/**
 * フォーム部品（`component` タグはカタログ語彙 `text_input` / `select` と共有）。
 */
export type FormField = { "component": "text_input" } & TextInputProps | { "component": "select" } & SelectProps;
