// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 表示範囲（南西 / 北東の角）。
 */
export type GeoBounds = { 
/**
 * 南端の緯度。
 */
south: number, 
/**
 * 西端の経度。
 */
west: number, 
/**
 * 北端の緯度。
 */
north: number, 
/**
 * 東端の経度。
 */
east: number, };
