// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 緯度経度（WGS84・度）。
 */
export type GeoPoint = { 
/**
 * 緯度（-90〜90）。
 */
lat: number, 
/**
 * 経度（-180〜180）。
 */
lng: number, };
