// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 検証エラー（コード＋メッセージ＋位置）。workflow の `ValidationError` と同型の設計。
 */
export type GuiValidationError = { 
/**
 * エラーコード（例: `gui.unknown_action_ref`）。
 */
code: string, 
/**
 * 人向け（かつ LLM の自己修正向け）メッセージ。
 */
message: string, 
/**
 * 紐付くツリー位置（例: `root.children[2].on_click`）。
 */
path: string | null, };
