// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HandlerKind } from "./HandlerKind";

/**
 * サーバハンドラ束縛。
 */
export type HandlerBinding = { id: string, handler: HandlerKind, };
