// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 明示登録のサーバ側ハンドラ束縛（Task 6.5 の②）。閉じた集合＝未知ハンドラは表現不可能。
 */
export type HandlerKind = "chat.submit";
