// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 旅程予定の種別。
 */
export type ItineraryKind = "activity" | "travel" | "food" | "lodging" | "sight";
