// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ItineraryKind } from "./ItineraryKind";

/**
 * 旅程の 1 予定。
 */
export type ItineraryItem = { 
/**
 * 時刻の表示文字列（「10:00」等・任意）。
 */
time: string | null, title: string, description: string | null, 
/**
 * 場所（任意）。
 */
location: string | null, 
/**
 * 種別（アイコン/配色の意味付け）。
 */
kind: ItineraryKind, };
