// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ItineraryItem } from "./ItineraryItem";

/**
 * 旅程の 1 日。
 */
export type ItineraryDay = { 
/**
 * 見出し（「1 日目」等・任意）。
 */
label: string | null, 
/**
 * 日付の表示文字列（「7/13(日)」等・任意）。
 */
date: string | null, items: Array<ItineraryItem>, };
