// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ItineraryDay } from "./ItineraryDay";

/**
 * 旅程カード（日ごとの時系列タイムライン）。
 */
export type ItineraryProps = { title: string | null, days: Array<ItineraryDay>, };
