// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KeyValueItem } from "./KeyValueItem";

/**
 * 定義リスト（キー: 値の詳細表示）。
 */
export type KeyValueProps = { title: string | null, items: Array<KeyValueItem>, };
