// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 知識スコープ（folders は配下全体・files は個別）。両方空の Some は保存時に拒否。
 */
export type KnowledgeScope = { folders: Array<string>, files: Array<string>, };
