// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 外部リンク（`https://` のみ・検証で強制）。
 */
export type LinkProps = { text: string, href: string, };
