// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MarkerKind } from "./MarkerKind";

/**
 * 地点マーカー。
 */
export type MapMarker = { 
/**
 * 緯度（-90〜90）。
 */
lat: number, 
/**
 * 経度（-180〜180）。
 */
lng: number, 
/**
 * ピンのラベル（地名など・任意）。
 */
label: string | null, 
/**
 * 補足の説明（任意）。
 */
description: string | null, 
/**
 * マーカー種別（配色/アイコンの意味付け）。
 */
kind: MarkerKind, };
