// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GeoBounds } from "./GeoBounds";
import type { GeoPoint } from "./GeoPoint";
import type { MapMarker } from "./MapMarker";
import type { MapRoute } from "./MapRoute";

/**
 * 地図（マーカー＋任意のルート）。
 */
export type MapProps = { 
/**
 * 初期表示の中心。
 */
center: GeoPoint, 
/**
 * 初期ズーム（0=世界全体〜22=建物）。省略時はフロントが markers/bounds から決める。
 */
zoom: number | null, 
/**
 * マーカー（地点ピン）。
 */
markers: Array<MapMarker>, 
/**
 * ルート（順序付き waypoint を結ぶ線・任意）。
 */
route: MapRoute | null, 
/**
 * 表示範囲（指定時は markers/center より優先して収める・任意）。
 */
bounds: GeoBounds | null, 
/**
 * 地図の見出し（任意）。
 */
title: string | null, };
