// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GeoPoint } from "./GeoPoint";
import type { RouteMode } from "./RouteMode";

/**
 * ルート（順序付き地点を結ぶ線）。
 */
export type MapRoute = { 
/**
 * 経由地（順序どおりに結ぶ・2 点以上）。
 */
waypoints: Array<GeoPoint>, 
/**
 * 移動手段（配色/表現の意味付け）。
 */
mode: RouteMode, };
