// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * マーカー種別（意味的バリアントのみ・配色は閉じた集合から選ぶ）。
 */
export type MarkerKind = "place" | "start" | "end" | "stop" | "lodging" | "food" | "sight";
