// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComponentPin } from "./ComponentPin";
import type { NamedComponentPin } from "./NamedComponentPin";

/**
 * ミニアプリ本文（artifact kind=mini_app の body JSONB）。
 */
export type MiniAppBody = { description: string, 
/**
 * 初期描画する UI スペック（kind=ui_spec・必須）。
 */
ui_spec: ComponentPin, 
/**
 * 初期コンテキストに適用する skill（kind=skill・任意）。
 */
skill: ComponentPin | null, 
/**
 * 束ねるワークフロー（kind=workflow・UI スペックの workflow 束縛はこの集合に限る）。
 */
workflows: Array<NamedComponentPin>, };
