// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * モデル/パラメータ既定（llm-gateway 呼び出しへ反映）。
 */
export type ModelDefaults = { 
/**
 * 論理モデル名（カタログ照合は llm-gateway 側）。
 */
model: string | null, 
/**
 * 0.0..=2.0。
 */
temperature: number | null, 
/**
 * 最大トークン。
 */
max_tokens: number | null, };
