// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 名前付きワークフロー参照（UI スペックの束縛照合・表示用の別名つき）。
 */
export type NamedComponentPin = { 
/**
 * 表示・参照用の別名（ミニアプリ内で一意）。
 */
alias: string, artifact_id: string, 
/**
 * JSON 経由の数値のため TS では number（bigint にしない）。
 */
version: number, };
