// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionRef } from "./ActionRef.js";
import type { PlanCardStep } from "./PlanCardStep.js";

/**
 * 実行前の計画とその承認導線。
 */
export type PlanCardProps = { 
/**
 * カード id（文書内で一意・フォーム/質問カードと同一名前空間）。
 */
id: string, 
/**
 * 見出し（省略時はフロントが「調査計画」を表示）。
 */
title: string | null, 
/**
 * 導入文（何を調べるか・任意）。
 */
intro: string | null, 
/**
 * 計画のステップ（順序付き）。
 */
steps: Array<PlanCardStep>, 
/**
 * 送信先アクション（`chat.submit` ハンドラのみ許可）。
 */
submit: ActionRef, 
/**
 * 開始ボタンのラベル（省略時「この計画で開始」）。
 */
submit_label: string | null, 
/**
 * 「修正する」の自由記述欄を出すか（既定 true）。
 * false にすると開始のみ（提示した計画を必ず通す用途）。
 */
allow_revise: boolean, };
