// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 計画の 1 ステップ。
 */
export type PlanCardStep = { title: string, 
/**
 * 補足（何をどこまで調べるか・任意）。
 */
description: string | null, };
