// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 選択肢 1 件（ラベル＋任意の説明）。
 */
export type QuestionOption = { 
/**
 * 選択肢のラベル（回答値になる）。
 */
label: string, 
/**
 * 選択肢の説明（カードの補足行・任意）。
 */
description: string | null, };
