// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QuestionOption } from "./QuestionOption";

/**
 * 1 問。`options` が空なら自由記述（テキストエリア）のみ。
 */
export type QuestionItem = { 
/**
 * 回答値のキー（カード内で一意）。
 */
id: string, 
/**
 * 短い見出しチップ（例「予算」「日程」・任意）。
 */
header: string | null, 
/**
 * 質問文（短くても長くてもよい）。
 */
question: string, 
/**
 * 選択肢（各カードはラベル＋説明。空なら自由記述のみ）。
 */
options: Array<QuestionOption>, 
/**
 * 複数選択可（既定は単一選択）。
 */
multi_select: boolean, 
/**
 * 選択肢外の自由記述（「その他」）を許す。
 */
allow_other: boolean, 
/**
 * 自由記述欄のプレースホルダ（options 無し or その他選択時）。
 */
placeholder: string | null, };
