// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionRef } from "./ActionRef";
import type { QuestionItem } from "./QuestionItem";

/**
 * AI からユーザーへの質問カード（複数問・ステップ提示）。
 *
 * `id` はフォームと同一名前空間で重複検査する（どちらも送信可能な単位のため）。
 */
export type QuestionCardProps = { 
/**
 * カード id（文書内で一意）。
 */
id: string, 
/**
 * 見出し（省略時はフロントが「AI からの質問」を表示）。
 */
title: string | null, 
/**
 * 導入文（何のための質問か・任意）。
 */
intro: string | null, 
/**
 * 送信先アクション（宣言済み束縛の参照のみ）。
 */
submit: ActionRef, 
/**
 * 質問（1 問ずつ提示する）。
 */
questions: Array<QuestionItem>, 
/**
 * 送信ボタンのラベル（省略時「回答する」）。
 */
submit_label: string | null, };
