// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SelectOption } from "./SelectOption";

/**
 * 単一選択（ラジオ群・select の視覚差し替え）。
 */
export type RadioGroupProps = { id: string, label: string, options: Array<SelectOption>, default: string | null, required: boolean, allow_other: boolean, };
