// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * レーティング（星の数など）。
 */
export type RatingProps = { id: string, label: string, 
/**
 * 最大値（省略時 5）。
 */
max: number | null, default: number | null, required: boolean, };
