// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 予約コンポーネントの props（プレースホルダ・props を持たない）。
 */
export type ReservedProps = Record<string, never>;
