// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 移動手段（意味的バリアントのみ）。
 */
export type RouteMode = "driving" | "walking" | "transit" | "flight";
