// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SelectOption } from "./SelectOption";

/**
 * 選択（宣言された選択肢のみ）。
 */
export type SelectProps = { id: string, label: string, options: Array<SelectOption>, required: boolean, default: string | null, };
