// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * コマンドの引数プリセット 1 件。
 */
export type SkillCommandVariant = { 
/**
 * コマンド名の後ろに置く引数（空文字＝引数なし）。
 */
args: string, 
/**
 * 補完候補に出す説明。
 */
summary: string, };
