// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScriptKind } from "./ScriptKind";

/**
 * skill 同梱 script 1 ファイル（インライン保存＝バージョンと一体で不変・再現性）。
 */
export type SkillScript = { 
/**
 * `scripts/<name>.<ext>` 形式の相対パス（`..`・絶対パスは拒否）。
 */
path: string, kind: ScriptKind, 
/**
 * 本文（実行はしない・保存のみ）。
 */
source: string, };
