// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommandPhase } from "./CommandPhase";

/**
 * コマンドの引数プリセット 1 件。
 */
export type SkillCommandVariant = { 
/**
 * コマンド名の後ろに置く引数（空文字＝引数なし）。
 */
args: string, 
/**
 * 補完候補に出す説明。
 */
summary: string, 
/**
 * この variant で起動したとき、実行前に**確認フェーズを通す**か（#400）。
 *
 * `None` は従来どおり（最初から全ツール）。`PlanFirst` は「質問カード → 計画カード →
 * 承認 → 実行」を**ツール提示で保証する**（instructions の門は実測で確率的にしか効かず、
 * 同じ指示で止まる run と素通りする run が出た）。判定は chat 側の
 * `crate::worker::gate` にあり、ここは skill が意図を宣言する場所。
 */
phase: CommandPhase | null, };
