// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FewShotExample } from "./FewShotExample";
import type { KnowledgeScope } from "./KnowledgeScope";
import type { ModelDefaults } from "./ModelDefaults";
import type { SkillScript } from "./SkillScript";
import type { ToolName } from "./ToolName";

/**
 * skill 本文（artifact kind=skill の body JSONB）。
 */
export type SkillBody = { 
/**
 * フロントマターの description 相当（name は artifact.name が正）。
 */
description: string, 
/**
 * SKILL.md 本文（用途・振る舞いを書く指示文。システムプロンプトへ注入される）。
 */
instructions: string, 
/**
 * 知識スコープ（RAG 参照範囲の限定）。None は全可読範囲。
 */
knowledge_scope: KnowledgeScope | null, 
/**
 * 許可ツール（None は全提示）。閉語彙照合・**縮小のみ**（破壊系の明示許可要求は無効化しない）。
 */
allowed_tools: Array<ToolName> | null, 
/**
 * モデル/パラメータ既定。
 */
model: ModelDefaults | null, 
/**
 * few-shot（user/assistant 対で履歴先頭に注入）。
 */
few_shot: Array<FewShotExample>, 
/**
 * script（`.shiki`=script-runtime / `.sh`=agent.invoke サンドボックス）。
 * **本フェーズでは保存のみ**（実行は呼び出し面・Phase 10 Stage B）。
 */
scripts: Array<SkillScript>, 
/**
 * 参照資料（storage node 参照のみ・実体二重持ちなし）。
 */
references: Array<string>, };
