// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SkillCommandVariant } from "./SkillCommandVariant";

/**
 * スキルをコンポーザから `/<name>` で起動するための宣言（#387）。
 *
 * **フロントにコマンド定義をハードコードしない**ための宣言。補完候補・引数のプリセットは
 * すべてここから来る（`GET /skills/catalog` で配る）。コマンドは能力を増やさない —
 * 起動の入口を作るだけで、実効権限は従来どおり「セッション配線 ∩ 実行主体 ReBAC ∩ skill 宣言」。
 */
export type SkillCommand = { 
/**
 * コマンド名（`/` は含めない）。`^[a-z0-9][a-z0-9-]*$`。
 */
name: string, 
/**
 * 入力欄のプレースホルダ（「調べたいことを入力」など）。
 */
hint: string | null, 
/**
 * 引数プリセット（`/deep-research auto` の `auto`）。空文字は引数なしの既定。
 */
variants: Array<SkillCommandVariant>, };
