// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * スライダー（数値範囲）。
 */
export type SliderProps = { id: string, label: string, min: number, max: number, step: number | null, default: number | null, };
