// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SourceItem } from "./SourceItem";

/**
 * RAG 引用元カード（タイトル＋抜粋＋スコア＋出典リンク）。
 */
export type SourceCardProps = { 
/**
 * 見出し（省略時はフロントが「出典」を表示）。
 */
title: string | null, 
/**
 * **ドメインのチップだけ**に畳んで出す（既定 false）。
 *
 * RAG の引用（数件・抜粋が意味を持つ）と、web 調査の出典一覧（十数件・どこを見たかが
 * 分かれば足りる）では要る密度が違う。後者を既定の縦積みで出すと、説明文つきの行が
 * 12 件並んで会話の末尾を占領する（実測でその状態になった）。詳しい出典はレポート本文の
 * 引用に付いているので、会話側は「どのドメインを見たか」だけでよい。
 */
compact: boolean, sources: Array<SourceItem>, };
