// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SourceItem } from "./SourceItem";

/**
 * RAG 引用元カード（タイトル＋抜粋＋スコア＋出典リンク）。
 */
export type SourceCardProps = { 
/**
 * 見出し（省略時はフロントが「出典」を表示）。
 */
title: string | null, sources: Array<SourceItem>, };
