// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 引用元 1 件。
 */
export type SourceItem = { title: string, 
/**
 * 抜粋（該当箇所の一節・任意）。
 */
snippet: string | null, 
/**
 * 出典 URL（https のみ・任意）。
 */
url: string | null, 
/**
 * 関連度スコア（0〜1 など・任意）。
 */
score: number | null, 
/**
 * 出典種別の短ラベル（PDF/Web/ノート等・任意）。
 */
label: string | null, };
