// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * KPI スタットタイル（数値＋前期比デルタ＋インライン sparkline）。
 *
 * `value` は表示用の整形済み文字列（例 `"¥1.2M"` `"98.3"`）。`delta` は前期比などの
 * 変化率で、正なら改善（↑・緑）／負なら悪化（↓・赤）として色付けする。
 */
export type StatProps = { 
/**
 * 指標名（例「今月の売上」）。
 */
label: string, 
/**
 * 表示値（整形済み文字列）。
 */
value: string, 
/**
 * 単位（例「件」「%」）。
 */
unit: string | null, 
/**
 * 前期比などの変化率（正=改善・負=悪化として色付け）。
 */
delta: number | null, 
/**
 * デルタの補足ラベル（例「前月比」）。
 */
delta_label: string | null, 
/**
 * インライン sparkline の値列（省略可・上限は validate が課す）。
 */
trend: Array<number>, 
/**
 * 補足キャプション。
 */
caption: string | null, };
