// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StepStatus } from "./StepStatus";

/**
 * ステップ 1 件。
 */
export type StepItem = { title: string, status: StepStatus, description: string | null, };
