// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StepItem } from "./StepItem";

/**
 * ステッパー（工程の進捗）。
 */
export type StepperProps = { steps: Array<StepItem>, };
