// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UiNode } from "./UiNode";

/**
 * タブ 1 枚（子ツリーを持つ）。
 */
export type TabItem = { label: string, children: Array<UiNode>, };
