// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CellAlign } from "./CellAlign";

/**
 * テーブル列定義。
 */
export type TableColumn = { label: string, align: CellAlign, };
