// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CellValue } from "./CellValue";
import type { TableColumn } from "./TableColumn";

/**
 * 表示専用テーブル（データは props 内・構造化データ連携は Phase 9）。
 */
export type TableProps = { title: string | null, columns: Array<TableColumn>, 
/**
 * 行（各行の長さは columns と一致・検証で強制）。
 */
rows: Array<Array<CellValue>>, };
