// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TabItem } from "./TabItem";

/**
 * タブ。
 */
export type TabsProps = { tabs: Array<TabItem>, };
