// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TextVariant } from "./TextVariant";

/**
 * プレーンテキスト（markdown/HTML は解釈しない）。
 */
export type TextProps = { text: string, variant: TextVariant, };
