// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * テキストの見た目（意味的バリアントのみ・任意スタイルは書けない）。
 */
export type TextVariant = "body" | "heading" | "caption";
