// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * テキスト入力。
 */
export type TextInputProps = { 
/**
 * フォーム値のキー（フォーム内で一意）。
 */
id: string, label: string, placeholder: string | null, multiline: boolean, required: boolean, default: string | null, };
