// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TimelineEvent } from "./TimelineEvent";

/**
 * タイムライン（時系列イベント列）。
 */
export type TimelineProps = { title: string | null, events: Array<TimelineEvent>, };
