// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BadgeTone } from "./BadgeTone";

/**
 * タイムラインの 1 件。
 */
export type TimelineEvent = { 
/**
 * 時刻/日付の表示文字列（任意）。
 */
time: string | null, title: string, description: string | null, 
/**
 * ドットの配色（layout の BadgeTone を共有）。
 */
tone: BadgeTone, };
