// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolName } from "./ToolName";

/**
 * ツール束縛。
 */
export type ToolBinding = { id: string, 
/**
 * ツール名（閉語彙・[`ALLOWED_ACTION_TOOLS`] 外は検証で拒否）。
 */
tool: ToolName, };
