// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ButtonProps } from "./ButtonProps";
import type { ChartSpec } from "./ChartSpec";
import type { ContainerProps } from "./ContainerProps";
import type { FormProps } from "./FormProps";
import type { LinkProps } from "./LinkProps";
import type { ReservedProps } from "./ReservedProps";
import type { StatProps } from "./StatProps";
import type { TableProps } from "./TableProps";
import type { TextProps } from "./TextProps";

/**
 * 信頼カタログのコンポーネントツリー（`component` タグ・閉じた集合）。
 */
export type UiNode = { "component": "container" } & ContainerProps | { "component": "text" } & TextProps | { "component": "link" } & LinkProps | { "component": "form" } & FormProps | { "component": "button" } & ButtonProps | { "component": "table" } & TableProps | { "component": "chart" } & ChartSpec | { "component": "stat" } & StatProps | { "component": "map" } & ReservedProps | { "component": "image" } & ReservedProps;
