// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionBinding } from "./ActionBinding";
import type { UiNode } from "./UiNode";

/**
 * UI スペック文書＝アクション束縛の宣言＋コンポーネントツリー。
 *
 * アクションはここで**宣言されたものだけ**が UI から参照でき（Task 6.5）、
 * ツリー側は [`ActionRef`] で id を参照するのみ（任意 URL・任意コードは書けない）。
 */
export type UiSpecDoc = { 
/**
 * スキーマ版（現在は 1 のみ）。
 */
version: number, 
/**
 * 宣言的アクション束縛（UI から実行できる操作の全て）。
 */
actions: Array<ActionBinding>, 
/**
 * ルートコンポーネント。
 */
root: UiNode, };
