// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 天候（意味的バリアントのみ・アイコンはフロントが対応付ける）。
 */
export type WeatherCondition = "sunny" | "partly_cloudy" | "cloudy" | "rain" | "storm" | "snow" | "fog";
