// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WeatherCondition } from "./WeatherCondition";

/**
 * 天気の 1 日。
 */
export type WeatherDay = { 
/**
 * 見出し（「今日」「月」等）。
 */
label: string, condition: WeatherCondition, 
/**
 * 最高気温（℃・任意）。
 */
high: number | null, 
/**
 * 最低気温（℃・任意）。
 */
low: number | null, 
/**
 * 降水確率（%・0〜100・任意）。
 */
precipitation: number | null, };
