// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WeatherDay } from "./WeatherDay";

/**
 * 天気カード（地点＋日別の天候）。
 */
export type WeatherProps = { location: string, title: string | null, days: Array<WeatherDay>, };
