// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ワークフロー参照（検証・解決で **artifact_id＋version が焼き込まれる**＝再現性）。
 *
 * LLM は `name` だけ書けばよく、[`SpecValidator`](crate::validator::SpecValidator) が
 * 発話ユーザーの viewer 権限で解決し、未指定 version は current にピンする。
 */
export type WorkflowPin = { 
/**
 * 参照名（tenant 内の workflow artifact 名）。
 */
name: string | null, 
/**
 * 解決済み artifact id（保存済みスペックでは常に Some）。
 */
artifact_id: string | null, 
/**
 * 解決済みバージョン（保存済みスペックでは常に Some）。
 */
version: bigint | null, };
