// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkflowPin } from "./WorkflowPin";

/**
 * ワークフロー起動束縛。
 */
export type WorkflowBinding = { id: string, workflow: WorkflowPin, };
